name: MubeenTesting

on:
    workflow_dispatch: 

jobs:
    say-hello-world:
        runs-on: ubuntu-22.04
        steps:
            - run: echo "Hello World!"
    say-something-else:
        runs-on: ubuntu-22.04
        steps:
            - run: print('I hate leetcode')
              shell: python
    

