name: MubeenTesting

on:
    push:
        branches:
            - "main"
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
        paths:
            - "backend/garbage/*.json"
            - "!backend/garbage/*.txt"    

    workflow_dispatch: 

jobs:
    say-hello-world:
        runs-on: ubuntu-22.04
        steps:
            - run: echo "Hello World!"
    say-something-else:
        runs-on: ubuntu-22.04
        steps:
            - run: print('I hate leetcode')
              shell: python
    third-job:
        runs-on: ubuntu-22.04
        needs:
            - say-hello-world
            - say-something-else
        steps:
            - run: echo "I depend on job 1 and job 2"
    fourth-job:
        runs-on: ubuntu-22.04
        needs:
            - say-something-else
            - third-job
        steps:
            - run: |
                print("This is fourth job")
                print("Next line of fourth job")
              shell: python

