name: MubeenTesting

on:
    push:
        branches:
            - "main"
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
        paths:
            - "backend/garbage/*.json"
            - "!backend/garbage/*.txt"    

    workflow_dispatch: 
 
env:
    WORKFLOW_VAR: workflow        

jobs:
    say-hello-world:
        runs-on: ubuntu-22.04
        env:
            HELLO_WORLD_VAR: hello_world
        steps:
          - name: say-hello-world-step-1
            env:
                HELLO_WORLD_STEP_ONE_VAR: hello_world_step_one_var
            run: |
                echo "WORKFLOW_VAR: $WORKFLOW_VAR"
                echo "HELLO_WORLD_VAR: $HELLO_WORLD_VAR"
                echo "HELLO_WORLD_STEP_ONE_VAR: $HELLO_WORLD_STEP_ONE_VAR"
    say-something-else:
        runs-on: ubuntu-22.04
        steps:
            - run: print('I hate leetcode')
              shell: python
    third-job:
        runs-on: ubuntu-22.04
        needs:
            - say-hello-world
            - say-something-else
        steps:
            - run: echo "I depend on job 1 and job 2"
    fourth-job:
        runs-on: ubuntu-22.04
        needs:
            - say-something-else
            - third-job
        steps:
            - run: |
                print("This is fourth job")
                print("Next line of fourth job")
              shell: python

