name: secretsAndVariables

on:
    workflow_dispatch: 

jobs:
    staging-environmnt:
        runs-on: ubuntu-22.04
        environment: staging
        env:
            environment_variable: ${{ vars.EXAMPLE_ENVIRONMENT_VARIABLE }}
        steps:
          - name: echoEnvironmentVariable
            run: |
                echo "Environment Variable: $environment_variable"


    